In [2]:
import torch

# 创建张量
x = torch.tensor([1, 2, 3])

print(x)

# 查看形状
print(x.shape)

# 矩阵乘法
a = torch.randn(2, 3)
print(a)
b = torch.randn(3, 4)
print(b)
c = a @ b

print(c)
print(c.shape)

tensor([1, 2, 3])
torch.Size([3])
tensor([[ 0.0379,  0.1276, -0.1520],
        [-1.3123,  0.4169, -1.4060]])
tensor([[-0.4822,  0.7955,  1.0647,  0.5759],
        [ 0.6174, -0.5915,  0.3316, -1.6128],
        [ 0.1719, -0.3012,  0.1020, -1.0527]])
tensor([[ 3.4397e-02,  4.5431e-04,  6.7198e-02, -2.4025e-02],
        [ 6.4856e-01, -8.6700e-01, -1.4024e+00,  5.1846e-02]])
torch.Size([2, 4])
