In [1]:
from sympy.codegen.fnodes import size
from sympy.printing.pytorch import torch

random_tensor = torch.rand(3,4)
print(random_tensor)

tensor([[0.2956, 0.8070, 0.5356, 0.9233],
        [0.2573, 0.9183, 0.3427, 0.6047],
        [0.0853, 0.8344, 0.7268, 0.8943]])


In [3]:
random_tensor = torch.rand(4,5,6)
random_tensor

tensor([[[0.4170, 0.4720, 0.0727, 0.6867, 0.0780, 0.7218],
         [0.1622, 0.3863, 0.7691, 0.6569, 0.4022, 0.9051],
         [0.5725, 0.3924, 0.6031, 0.8517, 0.3977, 0.9345],
         [0.2488, 0.2701, 0.7600, 0.6971, 0.0776, 0.5860],
         [0.0062, 0.8225, 0.0521, 0.1492, 0.5400, 0.0610]],

        [[0.3092, 0.4473, 0.3492, 0.2787, 0.7677, 0.6735],
         [0.5892, 0.1707, 0.6814, 0.9057, 0.6302, 0.8187],
         [0.5559, 0.9444, 0.5048, 0.4415, 0.7833, 0.7246],
         [0.3423, 0.8180, 0.9798, 0.2053, 0.7209, 0.7969],
         [0.2784, 0.5582, 0.5662, 0.2804, 0.2219, 0.6888]],

        [[0.2892, 0.8324, 0.2091, 0.6161, 0.7375, 0.6346],
         [0.3961, 0.3993, 0.8370, 0.8887, 0.6781, 0.5638],
         [0.8362, 0.1736, 0.1083, 0.3077, 0.4546, 0.8491],
         [0.8817, 0.1158, 0.0757, 0.2559, 0.4588, 0.0206],
         [0.4001, 0.0682, 0.9809, 0.5912, 0.1953, 0.0190]],

        [[0.2624, 0.4457, 0.3243, 0.9036, 0.2743, 0.0205],
         [0.8274, 0.8455, 0.5796, 0.6069, 0.3498, 

In [5]:
random_tensor = torch.rand(2,3,4,5)
random_tensor

tensor([[[[6.0594e-01, 4.0605e-01, 7.1399e-01, 6.1711e-01, 3.8717e-01],
          [8.1739e-01, 7.6285e-01, 1.5683e-01, 7.8325e-02, 8.3541e-01],
          [6.4182e-01, 7.4624e-01, 4.9421e-01, 5.3314e-01, 6.1968e-01],
          [8.6980e-01, 5.5467e-01, 6.6824e-01, 9.3967e-01, 4.0829e-04]],

         [[3.6966e-01, 1.7196e-01, 6.0337e-01, 1.5704e-01, 9.8944e-01],
          [9.5267e-01, 9.9923e-01, 7.8516e-01, 2.9615e-02, 4.0558e-02],
          [2.6278e-01, 8.3994e-01, 2.2607e-01, 6.4590e-01, 5.7070e-01],
          [4.0002e-01, 6.3575e-01, 9.0157e-01, 3.1960e-02, 5.4197e-01]],

         [[4.9150e-01, 2.2553e-01, 4.4903e-01, 7.9033e-01, 2.9363e-01],
          [9.9953e-01, 8.3295e-01, 1.7495e-01, 9.0749e-01, 5.9026e-01],
          [8.5280e-01, 8.9260e-01, 8.6865e-01, 6.6866e-01, 2.9716e-01],
          [8.8034e-01, 2.7349e-02, 3.3098e-01, 2.0818e-01, 2.4052e-01]]],


        [[[7.0488e-01, 8.9256e-01, 3.2463e-01, 8.5670e-01, 1.4633e-01],
          [4.9634e-01, 7.7646e-01, 1.1362e-02, 1.9170e-0

In [6]:
random_tensor.ndim

4

In [7]:
random_tensor.shape

torch.Size([2, 3, 4, 5])

In [11]:
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, colour
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

Zeros and ones

In [12]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [14]:
random_tensor = torch.rand(3,4)
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [15]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [16]:
ones.dtype,ones.ndim,ones.shape

(torch.float32, 2, torch.Size([3, 4]))

In [17]:
torch.range(0,10)

C:\Users\totoro\AppData\Local\Temp\ipykernel_13024\497691777.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [4]:
import torch
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
x = torch.randn(1,3)
x

tensor([[ 0.8112, -1.4140, -0.4257]])

In [14]:
a = torch.arange(start=0,end=1000,step=90)
a

tensor([  0,  90, 180, 270, 360, 450, 540, 630, 720, 810, 900, 990])

In [17]:
b = torch.zeros_like(input=a)
print(b)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
