In [7]:
from sympy.printing.pytorch import torch

float_32_tensor = torch.tensor(size=[3.0, 6.0, 9.0],
                               dtype=torch.float32,
                               device='cpu',
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [8]:
float_32_tensor.dtype

torch.float16

In [11]:
float_32_tensor.ndim, float_32_tensor.shape, float_32_tensor.device, float_32_tensor.requires_grad

(1, torch.Size([3]), device(type='cpu'), False)

In [17]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [18]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [23]:
int_32_tensor = torch.tensor([3, 6, 9]
                             , dtype=torch.int32
                             , device='cpu')
int_32_tensor


tensor([3, 6, 9], dtype=torch.int32)

In [22]:
int_32_tensor * float_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [24]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.0090, 0.4487, 0.1969, 0.1812],
        [0.6068, 0.8353, 0.5712, 0.7154],
        [0.3366, 0.5908, 0.5462, 0.0108]])

In [29]:
some_tensor

tensor([[0.0090, 0.4487, 0.1969, 0.1812],
        [0.6068, 0.8353, 0.5712, 0.7154],
        [0.3366, 0.5908, 0.5462, 0.0108]])

In [30]:
some_tensor.size

<function Tensor.size>

In [31]:
some_tensor.device

device(type='cpu')

In [32]:
some_tensor.shape

torch.Size([3, 4])

In [33]:
some_tensor.dtype

torch.float32

In [34]:
some_tensor.ndim

2