### Manipulating Tensor

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [1]:
import torch

tensor = torch.tensor([1, 2, 3])
print(tensor)
print(tensor + 100)

tensor([1, 2, 3])
tensor([101, 102, 103])


In [2]:
tensor * 10

tensor([10, 20, 30])

In [3]:
tensor - 10

tensor([-9, -8, -7])

In [6]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix multiplication

* Element-wise multiplication
* Matrix multiplication (dot product)

In [7]:
tensor * tensor

tensor([1, 4, 9])

In [8]:
torch.matmul(tensor, tensor)

tensor(14)

In [9]:
tensor @ tensor

tensor(14)

In [13]:
a = torch.randn(2, 3)
b = torch.randn(3, 4)
print(a)
print(b)
torch.matmul(a, b)
print(a @ b)

tensor([[-1.1855, -0.4844,  0.6441],
        [ 0.8556,  0.1965,  2.1974]])
tensor([[-1.6775,  1.2669,  0.1035, -1.0658],
        [-0.4295, -0.6753,  0.2392,  0.8575],
        [ 0.1357, -0.5320,  1.4394, -0.0898]])
tensor([[ 2.2841, -1.5175,  0.6886,  0.7903],
        [-1.2215, -0.2178,  3.2985, -0.9406]])


In [21]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
print(tensor_A.shape)

tensor_B = torch.tensor([[2, 3],
                         [5, 6],
                         [8, 9]])
print(tensor_B.shape)

# tensor_A @ tensor_B

tensor_B = tensor_B.T
print(tensor_B.shape)

tensor_A @ tensor_B

torch.Size([3, 2])
torch.Size([3, 2])
torch.Size([2, 3])


tensor([[ 8, 17, 26],
        [18, 39, 60],
        [28, 61, 94]])