### Reshaping, Stacking, Squeezing and Unsqueezing
* Reshaping - reshape an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory
as the original tensor
* Stacking - combine multiple tensors on top of each other(vstack) or side by side
(hstack)
* Squeeze - removes all '1' dimensions from a tensor
* Unsqueeze - add a '1' dimensions to a target tensor
* Permute - Return a view of the input with dimensions permuted(swapped) in a certain way

In [1]:
import torch

x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [6]:
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape, x_reshaped.size()

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]),
 torch.Size([9, 1]))

In [7]:
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [8]:
z[:,0] = 5
print(z)
print(x)

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])


In [12]:
x_stacked = torch.stack([x,x,x,x],dim=1)
print(x_stacked)

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])


In [2]:
import torch
x = torch.zeros(2,1,2,1,2)
x.size()

y = torch.squeeze(x)
y.size()

y=torch.squeeze(x,0)
y.size()

y=torch.squeeze(x,1)
y.size()

torch.Size([2, 2, 1, 2])

In [8]:
x = torch.arange(1,10)
print(x)
y = x.reshape(1,3,3)
print(y)
print(y[0])

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
