### Reproducibility (trying to make random out of random)

In short how a neural networks leans

start with random numbers -> tensor operations -> update random numbers to try and make them of the data -> again -> again

To reduce the randomness in neural networks and PyTorch comes the concept of a random seed

Essentially what the random seed does is "flavour" the randomness

In [4]:
import torch

a = torch.rand(3,4)
b = torch.rand(3,4)
print(a)
print(b)
print(a==b)

tensor([[0.0988, 0.2296, 0.0608, 0.5340],
        [0.6323, 0.2648, 0.1185, 0.2405],
        [0.9505, 0.3156, 0.1630, 0.9599]])
tensor([[0.8267, 0.0595, 0.1970, 0.8028],
        [0.6253, 0.1929, 0.7807, 0.0609],
        [0.7653, 0.0062, 0.0177, 0.1251]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [6]:
import torch

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
a = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
b = torch.rand(3,4)
print(a)
print(b)
print(a==b)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
